// Copyright (C) 2013 Filipe Militao <filipe.militao@cs.cmu.edu>
// GPL v3 Licensed http://www.gnu.org/licenses/

// FIXME: all this code is completely broken will work with node.js eventually

/*
 * Console mode of prototype.
 * using Node.js http://nodejs.org/
 * 
 */

console.log('== Running Test-Prototype Console mode ==');

if (process.argv.length < 3) {
    console.log('ERROR: expecting argument with file to parse');
    console.log('USAGE: node [options] main.js [FILE]');
    return process.exit(1);
}

var file = process.argv[2];
console.log("Using \"" + file + "\" as processing file.");

var fs = require('fs');

// fetchs the given source file
try {
    var source_code = fs.readFileSync(file, 'utf8');
    //console.log(source_code);
} catch (error) {
    console.error("ERROR: " + error);
    return process.exit(1);
}

// We are using the *GENERATED* grammar file.
// It was generated by installing jison with the command:
// 'sudo npm install jison -g'
// and then calling jison with our grammar:
// 'jison grammar.jison'
// which resulted in the 'grammar.js' file that we now 'hard import'
eval(fs.readFileSync('../web/grammar.js', 'utf8'));

console.log("Parse result:");

console.log( new grammar.Parser().parse(source_code) );

console.log("done.");
process.exit(0);
